# Generated by Django 5.2.8 on 2025-11-25 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coberturaisp',
            name='archivo_fisico',
            field=models.FileField(blank=True, null=True, upload_to='uploads/kmz/', verbose_name='Archivo KMZ original'),
        ),
        migrations.AddField(
            model_name='coberturaisp',
            name='usuario_subida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que subió'),
        ),
    ]
