# Generated by Django 5.2.8 on 2025-12-13 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agregar_campos_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISPUploadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del ISP')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token de acceso')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración (opcional)')),
                ('archivos_subidos', models.IntegerField(default=0, verbose_name='Total de archivos subidos')),
                ('ultima_subida', models.DateTimeField(blank=True, null=True, verbose_name='Última subida')),
            ],
            options={
                'verbose_name': 'Token de ISP',
                'verbose_name_plural': 'Tokens de ISPs',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='BulkQueryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_entrada', models.FileField(upload_to='bulk_queries/input/', verbose_name='Archivo CSV de entrada')),
                ('archivo_salida', models.FileField(blank=True, null=True, upload_to='bulk_queries/output/', verbose_name='Archivo CSV de salida')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('total_registros', models.IntegerField(default=0, verbose_name='Total de registros')),
                ('registros_procesados', models.IntegerField(default=0, verbose_name='Registros procesados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('error_mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje de error')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_queries', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Consulta Masiva',
                'verbose_name_plural': 'Consultas Masivas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
